command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"

env:
  - name: APP_ENV
    value: "dev"
  - name: CATALOG_NAME
    value: "shared"
  - name: SCHEMA_NAME
    value: "fashion_recommendations"
  - name: VOLUME_PATH
    value: "/Volumes/shared/fashion_recommendations/data"

  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "databricks.warehouse.fashion-warehouse"
