command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"

env:
  - name: APP_ENV
    value: "dev"
  - name: CATALOG_NAME
    value: "jongseob_demo"
  - name: SCHEMA_NAME
    value: "fashion_recommendations"
  - name: VOLUME_PATH
    value: "/Volumes/jongseob_demo/fashion_recommendations/data"

  # Optional: if you added a "SQL warehouse" resource in the Apps UI
  # this injects the warehouse id into env for your db.py to pick up
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "sql-warehouse"
